/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { ApiAction } from "../../commons/types/ApiAction";

export const ActionsResponse: core.serialization.Schema<serializers.ActionsResponse.Raw, Flatfile.ActionsResponse> =
    core.serialization.list(ApiAction);

export declare namespace ActionsResponse {
    type Raw = ApiAction.Raw[];
}
