/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { Action } from "../../commons/types/Action";

export const Actions: core.serialization.Schema<serializers.Actions.Raw, Flatfile.Actions> =
    core.serialization.list(Action);

export declare namespace Actions {
    type Raw = Action.Raw[];
}
