/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const PromptTypeEnum: core.serialization.Schema<serializers.PromptTypeEnum.Raw, Flatfile.PromptTypeEnum> =
    core.serialization.enum_(["AI_ASSIST", "CONSTRAINT_GENERATION"]);

export declare namespace PromptTypeEnum {
    type Raw = "AI_ASSIST" | "CONSTRAINT_GENERATION";
}
