/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * When both distinct and includeCounts are true, the count of distinctdeprecated field values will be returned
 *
 * @example
 *     true
 */
export type IncludeCountsDeprecated = boolean;
