/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Flatfile from "../../../../../api/index";
import * as core from "../../../../../core";

export const UpdateUserRequest: core.serialization.Schema<
    serializers.UpdateUserRequest.Raw,
    Flatfile.UpdateUserRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    dashboard: core.serialization.number().optional(),
});

export declare namespace UpdateUserRequest {
    export interface Raw {
        name?: string | null;
        dashboard?: number | null;
    }
}
