/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const SheetTransformConfig: core.serialization.ObjectSchema<
    serializers.SheetTransformConfig.Raw,
    Flatfile.SheetTransformConfig
> = core.serialization.object({
    sourceSheetIds: core.serialization.list(core.serialization.string()),
    destinationSheetIds: core.serialization.list(core.serialization.string()),
});

export declare namespace SheetTransformConfig {
    export interface Raw {
        sourceSheetIds: string[];
        destinationSheetIds: string[];
    }
}
