/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const ApiCredentials: core.serialization.ObjectSchema<serializers.ApiCredentials.Raw, Flatfile.ApiCredentials> =
    core.serialization.object({
        clientId: core.serialization.string(),
        secret: core.serialization.string(),
    });

export declare namespace ApiCredentials {
    interface Raw {
        clientId: string;
        secret: string;
    }
}
