/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const PersonalAccessTokenId: core.serialization.Schema<
    serializers.PersonalAccessTokenId.Raw,
    Flatfile.PersonalAccessTokenId
> = core.serialization.string();

export declare namespace PersonalAccessTokenId {
    export type Raw = string;
}
