/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

/**
 * Properties used to create a new event
 *
 * @example
 *     {
 *         topic: Flatfile.EventTopic.WorkbookUpdated,
 *         payload: {
 *             "recordsAdded": 100
 *         },
 *         domain: Flatfile.Domain.Workbook,
 *         context: {
 *             accountId: "us_acc_YOUR_ID",
 *             actorId: "us_key_SOME_KEY",
 *             environmentId: "us_env_YOUR_ID",
 *             spaceId: "us_sp_YOUR_ID",
 *             workbookId: "us_wb_YOUR_ID"
 *         }
 *     }
 */
export interface CreateEventConfig extends Flatfile.BaseEvent {
    topic: Flatfile.EventTopic;
    payload: Record<string, any>;
    /** Date the event was deleted */
    deletedAt?: Date;
}
