/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The topic of the event
 *
 * @example
 *     Flatfile.EventTopic.FileCreated
 */
export type EventTopic =
    | "agent:created"
    | "agent:updated"
    | "agent:deleted"
    | "space:created"
    | "space:updated"
    | "space:deleted"
    | "document:created"
    | "document:updated"
    | "document:deleted"
    | "workbook:created"
    | "workbook:updated"
    | "workbook:deleted"
    | "sheet:created"
    | "sheet:updated"
    | "sheet:deleted"
    | "file:created"
    | "file:updated"
    | "file:deleted"
    | "job:created"
    | "job:updated"
    | "job:deleted"
    | "job:completed"
    | "job:ready"
    | "job:scheduled"
    | "job:outcome_acknowledged"
    | "job:failed"
    | "commit:created"
    | "commit:updated"
    | "layer:created";

export const EventTopic = {
    AgentCreated: "agent:created",
    AgentUpdated: "agent:updated",
    AgentDeleted: "agent:deleted",
    SpaceCreated: "space:created",
    SpaceUpdated: "space:updated",
    SpaceDeleted: "space:deleted",
    DocumentCreated: "document:created",
    DocumentUpdated: "document:updated",
    DocumentDeleted: "document:deleted",
    WorkbookCreated: "workbook:created",
    WorkbookUpdated: "workbook:updated",
    WorkbookDeleted: "workbook:deleted",
    SheetCreated: "sheet:created",
    SheetUpdated: "sheet:updated",
    SheetDeleted: "sheet:deleted",
    FileCreated: "file:created",
    FileUpdated: "file:updated",
    FileDeleted: "file:deleted",
    JobCreated: "job:created",
    JobUpdated: "job:updated",
    JobDeleted: "job:deleted",
    JobCompleted: "job:completed",
    JobReady: "job:ready",
    JobScheduled: "job:scheduled",
    JobOutcomeAcknowledged: "job:outcome_acknowledged",
    JobFailed: "job:failed",
    CommitCreated: "commit:created",
    CommitUpdated: "commit:updated",
    LayerCreated: "layer:created",
} as const;
