/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@fern-api/flatfile";

/**
 * The attributes of the event
 */
export interface EventAttributes {
    /** The progress of the event within a collection of iterable events */
    progress?: Flatfile.Progress;
}
