/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface JobPayload {
    type: Flatfile.JobPayloadType;
    operation: Flatfile.JobOperationType;
}
