/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface JobStartedEvent extends Flatfile.BaseEvent {
    payload: Flatfile.JobPayload;
}
