/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface RecordsDeletedEvent extends Flatfile.BaseEvent {
    payload: Record<string, any>;
}
