/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

export interface UpdateResolutionRequest {
    /** Array of record-specific resolutions to update */
    resolvedRecords: Flatfile.ResolvedRecords[];
}
