/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

/**
 * Request to perform bulk flag operations
 *
 * @example
 *     {
 *         operation: Flatfile.FlagOperation.Apply,
 *         slug: "important",
 *         flag: {
 *             label: "Important",
 *             colorHex: "#0090FF"
 *         },
 *         snapshotLabel: "Before important flag application"
 *     }
 *
 * @example
 *     {
 *         operation: Flatfile.FlagOperation.Delete,
 *         slug: "important",
 *         exceptions: ["rec_123", "rec_456"]
 *     }
 */
export interface BulkMutateFlagsRequest {
    /** The operation to perform */
    operation: Flatfile.FlagOperation;
    /** The flag slug to operate on */
    slug: string;
    /** Flag data for apply/update operations */
    flag?: Flatfile.FlagMutationData;
    /** Record IDs to exclude from the operation */
    exceptions?: string[];
    /** Query string to filter records */
    query?: string;
    /** Filter object to apply to records */
    filter?: any;
    /** Field to filter on */
    filterField?: string;
    /** Value to search for */
    searchValue?: string;
    /** Field to search in */
    searchField?: string;
    /** General search query */
    q?: string;
    /** Specific record IDs to target */
    ids?: string[];
    /** Label for snapshot before mutation */
    snapshotLabel?: string;
}
