/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of flag operation to perform
 */
export type FlagOperation = "apply" | "update" | "delete" | "replace";
export const FlagOperation = {
    Apply: "apply",
    Update: "update",
    Delete: "delete",
    Replace: "replace",
} as const;
