/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { DataClipId } from "../../commons/types/DataClipId";
import { SheetId } from "../../commons/types/SheetId";

export const AddRecordsToDataClipJobConfig: core.serialization.ObjectSchema<
    serializers.AddRecordsToDataClipJobConfig.Raw,
    Flatfile.AddRecordsToDataClipJobConfig
> = core.serialization.object({
    dataClipId: DataClipId,
    sheetId: SheetId,
});

export declare namespace AddRecordsToDataClipJobConfig {
    interface Raw {
        dataClipId: DataClipId.Raw;
        sheetId: SheetId.Raw;
    }
}
