/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { EnumValue } from "./EnumValue";

export const CategoryMapping: core.serialization.ObjectSchema<
    serializers.CategoryMapping.Raw,
    Flatfile.CategoryMapping
> = core.serialization.object({
    sourceValue: EnumValue.optional(),
    destinationValue: EnumValue.optional(),
});

export declare namespace CategoryMapping {
    export interface Raw {
        sourceValue?: EnumValue.Raw | null;
        destinationValue?: EnumValue.Raw | null;
    }
}
