/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const Driver: core.serialization.Schema<serializers.Driver.Raw, Flatfile.Driver> = core.serialization.enum_([
    "csv",
]);

export declare namespace Driver {
    export type Raw = "csv";
}
