/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { JobOutcomeTriggerType } from "./JobOutcomeTriggerType";
import { JobOutcomeTriggerAudience } from "./JobOutcomeTriggerAudience";

export const JobOutcomeTriggerDetails: core.serialization.ObjectSchema<
    serializers.JobOutcomeTriggerDetails.Raw,
    Flatfile.JobOutcomeTriggerDetails
> = core.serialization.object({
    type: JobOutcomeTriggerType,
    audience: JobOutcomeTriggerAudience.optional(),
});

export declare namespace JobOutcomeTriggerDetails {
    interface Raw {
        type: JobOutcomeTriggerType.Raw;
        audience?: JobOutcomeTriggerAudience.Raw | null;
    }
}
