/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const JobPartExecution: core.serialization.Schema<serializers.JobPartExecution.Raw, Flatfile.JobPartExecution> =
    core.serialization.enum_(["sequential", "parallel"]);

export declare namespace JobPartExecution {
    export type Raw = "sequential" | "parallel";
}
