/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const JobSplitDetails: core.serialization.ObjectSchema<
    serializers.JobSplitDetails.Raw,
    Flatfile.JobSplitDetails
> = core.serialization.object({
    parts: core.serialization.lazy(async () => (await import("../../..")).JobParts),
    runInParallel: core.serialization.boolean().optional(),
});

export declare namespace JobSplitDetails {
    interface Raw {
        parts: serializers.JobParts.Raw;
        runInParallel?: boolean | null;
    }
}
