/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const ResourceJobSubject: core.serialization.ObjectSchema<
    serializers.ResourceJobSubject.Raw,
    Flatfile.ResourceJobSubject
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace ResourceJobSubject {
    export interface Raw {
        id: string;
    }
}
