/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

/**
 * A single row of data in a Sheet, including links to related rows
 */
export interface RecordWithLinks extends Flatfile.Record_ {}
