/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

/**
 * A single row of data in a Sheet, including links to related rows
 *
 * @example
 *     {
 *         "firstName": {
 *             value: "John",
 *             messages: [],
 *             valid: true,
 *             updatedAt: "2023-11-20T16:59:40.286Z"
 *         },
 *         "lastName": {
 *             value: "Smith",
 *             messages: [],
 *             valid: true,
 *             updatedAt: "2023-11-20T16:59:40.286Z"
 *         },
 *         "email": {
 *             value: "john.smith@example.com",
 *             messages: [],
 *             valid: true,
 *             updatedAt: "2023-11-20T16:59:40.286Z"
 *         }
 *     }
 *
 * @example
 *     {
 *         "firstName": {
 *             value: "Suzie",
 *             messages: [],
 *             valid: true,
 *             updatedAt: "2023-11-20T16:59:40.286Z"
 *         },
 *         "lastName": {
 *             value: "Q",
 *             messages: [],
 *             valid: true,
 *             updatedAt: "2023-11-20T16:59:40.286Z"
 *         },
 *         "email": {
 *             value: "suzie.q@example.com",
 *             messages: [],
 *             valid: true,
 *             updatedAt: "2023-11-20T16:59:40.286Z"
 *         }
 *     }
 */
export type RecordDataWithLinks = Record<string, Flatfile.CellValueWithLinks>;
