/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

/**
 * A single row of data in a Sheet
 *
 * @example
 *     {
 *         "firstName": {
 *             value: "John",
 *             messages: [],
 *             valid: true
 *         },
 *         "lastName": {
 *             value: "Smith",
 *             messages: [],
 *             valid: true
 *         },
 *         "email": {
 *             value: "john.smith@example.com",
 *             messages: [],
 *             valid: true
 *         }
 *     }
 */
export type RecordData = Record<string, Flatfile.CellValue>;
