/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ValidationSource =
    | "required-constraint"
    | "unique-constraint"
    | "custom-logic"
    | "unlinked"
    | "invalid-option"
    | "is-artifact";
export const ValidationSource = {
    RequiredConstraint: "required-constraint",
    UniqueConstraint: "unique-constraint",
    CustomLogic: "custom-logic",
    Unlinked: "unlinked",
    InvalidOption: "invalid-option",
    IsArtifact: "is-artifact",
} as const;
