/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const Secret: core.serialization.ObjectSchema<serializers.Secret.Raw, Flatfile.Secret> = core.serialization
    .object({
        id: core.serialization.lazy(async () => (await import("../../..")).SecretId),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).WriteSecret));

export declare namespace Secret {
    interface Raw extends serializers.WriteSecret.Raw {
        id: serializers.SecretId.Raw;
    }
}
