/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

export interface CompositeUniqueConstraintConfig {
    /** Custom validation message to display when the constraint fails */
    message?: string;
    /** Validation level (error, warn, info). Defaults to error. */
    level?: Flatfile.ValidationType;
}
