/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@flatfile/api-beta";

/**
 * A field with one or many records
 */
export type FieldResponse = Record<string, Flatfile.FieldsData>;
