/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@flatfile/api";

/**
 * A place to store tabular data
 */
export interface Sheet {
    id: Flatfile.SheetId;
    workbookId?: Flatfile.WorkbookId;
    name: string;
    config?: Flatfile.SheetConfig;
    countRecords?: Flatfile.RecordCounts;
}
