/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface SheetConfigOrUpdate extends Flatfile.SheetConfigUpdate, Flatfile.SheetUpdate {}
