/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const RestoreOptions: core.serialization.ObjectSchema<serializers.RestoreOptions.Raw, Flatfile.RestoreOptions> =
    core.serialization.object({
        created: core.serialization.boolean(),
        updated: core.serialization.boolean(),
        deleted: core.serialization.boolean(),
    });

export declare namespace RestoreOptions {
    interface Raw {
        created: boolean;
        updated: boolean;
        deleted: boolean;
    }
}
