/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const EventAttributes: core.serialization.ObjectSchema<
    serializers.EventAttributes.Raw,
    Flatfile.EventAttributes
> = core.serialization.object({
    targetUpdatedAt: core.serialization.date().optional(),
    progress: core.serialization.lazyObject(async () => (await import("../../..")).Progress).optional(),
});

export declare namespace EventAttributes {
    interface Raw {
        targetUpdatedAt?: string | null;
        progress?: serializers.Progress.Raw | null;
    }
}
