/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const WorkbookUpdatedEvent: core.serialization.ObjectSchema<
    serializers.WorkbookUpdatedEvent.Raw,
    Flatfile.WorkbookUpdatedEvent
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseEvent));

export declare namespace WorkbookUpdatedEvent {
    interface Raw extends serializers.BaseEvent.Raw {}
}
