/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class FlatfileTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, FlatfileTimeoutError.prototype);
    }
}
