/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const CanvasAreaType: core.serialization.Schema<serializers.CanvasAreaType.Raw, Flatfile.CanvasAreaType> =
    core.serialization.enum_([
        "mapping",
        "header",
        "agent",
        "form",
        "sheet",
        "sheets",
        "workbook",
        "document",
        "file",
        "iframe",
    ]);

export declare namespace CanvasAreaType {
    type Raw =
        | "mapping"
        | "header"
        | "agent"
        | "form"
        | "sheet"
        | "sheets"
        | "workbook"
        | "document"
        | "file"
        | "iframe";
}
