/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@fern-api/flatfile";
import * as core from "../../../../core";

export const Document: core.serialization.ObjectSchema<serializers.Document.Raw, Flatfile.Document> = core.serialization
    .object({
        id: core.serialization.lazy(async () => (await import("../../..")).DocumentId),
        spaceId: core.serialization.lazy(async () => (await import("../../..")).SpaceId).optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).DocumentConfig));

export declare namespace Document {
    interface Raw extends serializers.DocumentConfig.Raw {
        id: serializers.DocumentId.Raw;
        spaceId?: serializers.SpaceId.Raw | null;
    }
}
