/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../../index";

/**
 * @example
 *     {
 *         environmentId: "us_env_YOUR_ID",
 *         agentId: "us_ag_YOUR_ID",
 *         spaceId: "us_sp_YOUR_ID",
 *         success: true,
 *         pageSize: 20,
 *         pageNumber: 1
 *     }
 */
export interface GetEnvironmentAgentExecutionsRequest {
    environmentId: Flatfile.EnvironmentId;
    agentId?: Flatfile.AgentId;
    spaceId?: Flatfile.SpaceId;
    success?: Flatfile.SuccessQueryParameter;
    pageSize?: Flatfile.PageSize;
    pageNumber?: Flatfile.PageNumber;
}
