/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../..";

/**
 * @example
 *     {
 *         fieldKey: "firstName",
 *         sortField: "firstName",
 *         sortDirection: Flatfile.SortDirection.Asc,
 *         filter: Flatfile.Filter.Valid
 *     }
 */
export interface GetFieldValuesRequestDeprecated {
    fieldKey?: Flatfile.FieldKeyDeprecated;
    sortField?: Flatfile.SortField;
    sortDirection?: Flatfile.SortDirection;
    filter?: Flatfile.Filter;
    /**
     * Name of field by which to filter records
     */
    filterField?: Flatfile.FilterField;
    /**
     * Number of records to return in a page (default 1000 if pageNumber included)
     */
    pageSize?: Flatfile.PageSize;
    /**
     * Based on pageSize, which page of records to return
     */
    pageNumber?: Flatfile.PageNumber;
    distinct?: Flatfile.DistinctDeprecated;
    includeCounts?: Flatfile.IncludeCountsDeprecated;
    /**
     * A value to find for a given field in a sheet. Wrap the value in "" for exact match
     */
    searchValue?: Flatfile.SearchValue;
}
