/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@fern-api/flatfile";

export interface GetRecordsRequest {
    versionId?: string;
    /**
     * Name of field by which to sort records
     */
    sortField?: string;
    /**
     * Sort direction - asc (ascending) or desc (descending)
     */
    sortDirection?: Flatfile.SortDirection;
    /**
     * Options to filter records
     */
    filter?: Flatfile.Filter;
    /**
     * Name of field by which to filter records
     */
    filterField?: string;
    /**
     * Number of records to return in a page (default 1000 if pageNumber included)
     */
    pageSize?: number;
    /**
     * Based on pageSize, which page of records to return
     */
    pageNumber?: number;
    /**
     * Include counts for the total records, valid records and records with errors
     */
    includeCounts?: boolean;
    /**
     * Search the entire sheet for the given value, returning matching rows
     */
    searchValue?: string;
}
