/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@flatfile/api-beta";

export interface GetRecordsCsvRequest {
    versionId?: string;
    sinceVersionId?: Flatfile.VersionId;
    sortField?: Flatfile.SortField;
    /**
     * Sort direction - asc (ascending) or desc (descending)
     */
    sortDirection?: Flatfile.SortDirection;
    /**
     * Options to filter records
     */
    filter?: Flatfile.Filter;
    filterField?: Flatfile.FilterField;
    searchValue?: Flatfile.SearchValue;
    searchField?: Flatfile.SearchField;
    /**
     * A list of record ids to download. If filter "all" is also specified,  then this is a list of record ids to exclude from the download.
     *
     */
    ids?: Flatfile.RecordId | Flatfile.RecordId[];
}
