/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListSheetCommitsRequest {
    /**
     * If true, only return commits that have been completed. If false, only return commits that have not been completed. If not provided, return all commits.
     */
    completed?: boolean;
}
