/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { VersionId } from "../../commons/types/VersionId";
import { CommitId } from "../../commons/types/CommitId";
import { SortField } from "../../commons/types/SortField";
import { SortDirection } from "../../commons/types/SortDirection";
import { Filter } from "../../commons/types/Filter";
import { FilterField } from "../../commons/types/FilterField";
import { SearchValue } from "../../commons/types/SearchValue";
import { SearchField } from "../../commons/types/SearchField";
import { RecordId } from "../../commons/types/RecordId";
import { EventId } from "../../commons/types/EventId";

export const ViewConfig: core.serialization.ObjectSchema<serializers.ViewConfig.Raw, Flatfile.ViewConfig> =
    core.serialization.object({
        versionId: VersionId.optional(),
        commitId: CommitId.optional(),
        sinceVersionId: VersionId.optional(),
        sinceCommitId: CommitId.optional(),
        sortField: SortField.optional(),
        sortDirection: SortDirection.optional(),
        filter: Filter.optional(),
        filterField: FilterField.optional(),
        searchValue: SearchValue.optional(),
        searchField: SearchField.optional(),
        ids: core.serialization.list(RecordId).optional(),
        pageSize: core.serialization.number().optional(),
        pageNumber: core.serialization.number().optional(),
        includeCounts: core.serialization.boolean().optional(),
        includeLength: core.serialization.boolean().optional(),
        includeLinks: core.serialization.boolean().optional(),
        includeMessages: core.serialization.boolean().optional(),
        for: EventId.optional(),
        q: core.serialization.string().optional(),
    });

export declare namespace ViewConfig {
    interface Raw {
        versionId?: VersionId.Raw | null;
        commitId?: CommitId.Raw | null;
        sinceVersionId?: VersionId.Raw | null;
        sinceCommitId?: CommitId.Raw | null;
        sortField?: SortField.Raw | null;
        sortDirection?: SortDirection.Raw | null;
        filter?: Filter.Raw | null;
        filterField?: FilterField.Raw | null;
        searchValue?: SearchValue.Raw | null;
        searchField?: SearchField.Raw | null;
        ids?: RecordId.Raw[] | null;
        pageSize?: number | null;
        pageNumber?: number | null;
        includeCounts?: boolean | null;
        includeLength?: boolean | null;
        includeLinks?: boolean | null;
        includeMessages?: boolean | null;
        for?: EventId.Raw | null;
        q?: string | null;
    }
}
