/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { OnboardingDatapointId } from "../../commons/types/OnboardingDatapointId";
import { OnboardingId } from "../../commons/types/OnboardingId";

export const OnboardingDatapoint: core.serialization.ObjectSchema<
    serializers.OnboardingDatapoint.Raw,
    Flatfile.OnboardingDatapoint
> = core.serialization.object({
    id: OnboardingDatapointId,
    onboardingId: OnboardingId,
    source: core.serialization.string().optional(),
    data: core.serialization.any(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
});

export declare namespace OnboardingDatapoint {
    export interface Raw {
        id: OnboardingDatapointId.Raw;
        onboardingId: OnboardingId.Raw;
        source?: string | null;
        data?: any;
        createdAt: string;
        updatedAt: string;
    }
}
