/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { CellValueWithCountsDeprecated } from "./CellValueWithCountsDeprecated";

export const CellsResponseDataDeprecated: core.serialization.Schema<
    serializers.CellsResponseDataDeprecated.Raw,
    Flatfile.CellsResponseDataDeprecated
> = core.serialization.record(core.serialization.string(), core.serialization.list(CellValueWithCountsDeprecated));

export declare namespace CellsResponseDataDeprecated {
    export type Raw = Record<string, CellValueWithCountsDeprecated.Raw[]>;
}
