/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../..";

/**
 * @example
 *     {
 *         ids: "us_sp_YOUR_ID"
 *     }
 */
export interface DeleteSpacesRequest {
    /**
     * List of ids for the spaces to be deleted
     */
    ids: Flatfile.SpaceId | Flatfile.SpaceId[];
}
