/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetGuidanceRequest {
    /**
     * Include the guide with the guidance
     */
    guide?: string;
}
