/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@flatfile/api";

export interface GuestSpace {
    id: Flatfile.SpaceId;
    lastAccessed?: Date;
}
