/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Flatfile from "../../../../../api";
import * as core from "../../../../../core";

export const AssignRoleRequest: core.serialization.Schema<
    serializers.AssignRoleRequest.Raw,
    Flatfile.AssignRoleRequest
> = core.serialization.object({
    actorId: core.serialization.lazy(async () => (await import("../../../..")).ActorIdUnion),
    resourceId: core.serialization.lazy(async () => (await import("../../../..")).ResourceIdUnion),
});

export declare namespace AssignRoleRequest {
    interface Raw {
        actorId: serializers.ActorIdUnion.Raw;
        resourceId: serializers.ResourceIdUnion.Raw;
    }
}
