/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@flatfile/api";
import * as core from "../../../../core";

export const CellValueWithLinks: core.serialization.ObjectSchema<
    serializers.CellValueWithLinks.Raw,
    Flatfile.CellValueWithLinks
> = core.serialization
    .object({
        links: core.serialization.lazy(async () => (await import("../../..")).Records).optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).CellValue));

export declare namespace CellValueWithLinks {
    interface Raw extends serializers.CellValue.Raw {
        links?: serializers.Records.Raw | null;
    }
}
