/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const RecordIndices: core.serialization.ObjectSchema<serializers.RecordIndices.Raw, Flatfile.RecordIndices> =
    core.serialization.object({
        id: core.serialization.string(),
        index: core.serialization.number(),
    });

export declare namespace RecordIndices {
    interface Raw {
        id: string;
        index: number;
    }
}
