/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { AgentVersion } from "./AgentVersion";

export const AgentVersionResponse: core.serialization.ObjectSchema<
    serializers.AgentVersionResponse.Raw,
    Flatfile.AgentVersionResponse
> = core.serialization.object({
    data: AgentVersion.optional(),
});

export declare namespace AgentVersionResponse {
    export interface Raw {
        data?: AgentVersion.Raw | null;
    }
}
