/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const Execution: core.serialization.ObjectSchema<serializers.Execution.Raw, Flatfile.Execution> =
    core.serialization.object({
        eventId: core.serialization.lazy(async () => (await import("../../..")).EventId),
        success: core.serialization.boolean(),
        createdAt: core.serialization.date(),
        completedAt: core.serialization.date(),
        duration: core.serialization.number(),
        topic: core.serialization.string(),
    });

export declare namespace Execution {
    interface Raw {
        eventId: serializers.EventId.Raw;
        success: boolean;
        createdAt: string;
        completedAt: string;
        duration: number;
        topic: string;
    }
}
