/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const GetDetailedAgentLogsResponse: core.serialization.ObjectSchema<
    serializers.GetDetailedAgentLogsResponse.Raw,
    Flatfile.GetDetailedAgentLogsResponse
> = core.serialization.object({
    pagination: core.serialization.lazyObject(async () => (await import("../../..")).Pagination).optional(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).DetailedAgentLog)
    ),
});

export declare namespace GetDetailedAgentLogsResponse {
    interface Raw {
        pagination?: serializers.Pagination.Raw | null;
        data: serializers.DetailedAgentLog.Raw[];
    }
}
