/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { AgentVersion } from "./AgentVersion";

export const ListAgentVersionsResponse: core.serialization.ObjectSchema<
    serializers.ListAgentVersionsResponse.Raw,
    Flatfile.ListAgentVersionsResponse
> = core.serialization.object({
    data: core.serialization.list(AgentVersion).optional(),
});

export declare namespace ListAgentVersionsResponse {
    export interface Raw {
        data?: AgentVersion.Raw[] | null;
    }
}
