/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../..";

export interface ActionsBulkCreateRequest {
    /**
     * The Space ID for which to create the Actions.
     */
    spaceId: Flatfile.SpaceId;
    body: Flatfile.ApiActionConfigs;
}
