/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { Onboarding } from "./Onboarding";

export const OnboardingsResponse: core.serialization.ObjectSchema<
    serializers.OnboardingsResponse.Raw,
    Flatfile.OnboardingsResponse
> = core.serialization.object({
    data: core.serialization.list(Onboarding),
});

export declare namespace OnboardingsResponse {
    export interface Raw {
        data: Onboarding.Raw[];
    }
}
