/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const MessageRole: core.serialization.Schema<serializers.MessageRole.Raw, Flatfile.MessageRole> =
    core.serialization.enum_(["system", "user", "assistant", "tool"]);

export declare namespace MessageRole {
    export type Raw = "system" | "user" | "assistant" | "tool";
}
