/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteApiKeyRequest {
    /**
     * ID of environment to search
     */
    environmentId: string;
    /**
     * The API key to delete
     */
    key: string;
}
