/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FlatfileV2 from "../../../../../index";

export interface BulkCreateWorkbooksResponse {
    /** List of created workbooks */
    data: FlatfileV2.v2.BulkCreateWorkbookResponse[];
}
