/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     Flatfile.RunbookStatus.Created
 *
 * @example
 *     Flatfile.RunbookStatus.Recording
 *
 * @example
 *     Flatfile.RunbookStatus.Executing
 *
 * @example
 *     Flatfile.RunbookStatus.Waiting
 *
 * @example
 *     Flatfile.RunbookStatus.Completed
 *
 * @example
 *     Flatfile.RunbookStatus.Failed
 *
 * @example
 *     Flatfile.RunbookStatus.Canceled
 */
export type RunbookStatus = "CREATED" | "RECORDING" | "EXECUTING" | "WAITING" | "COMPLETED" | "FAILED" | "CANCELED";

export const RunbookStatus = {
    Created: "CREATED",
    Recording: "RECORDING",
    Executing: "EXECUTING",
    Waiting: "WAITING",
    Completed: "COMPLETED",
    Failed: "FAILED",
    Canceled: "CANCELED",
} as const;
