/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

/**
 * @example
 *     {
 *         data: {
 *             id: "us_fl_YOUR_ID",
 *             name: "Test File",
 *             description: "This is a test file",
 *             ext: "csv",
 *             mimetype: "text/csv",
 *             encoding: "7bit",
 *             status: Flatfile.ModelFileStatusEnum.Partial,
 *             mode: Flatfile.Mode.Import,
 *             size: 81953,
 *             bytesReceived: 81593,
 *             createdAt: "2023-11-15T19:31:33.015Z",
 *             updatedAt: "2023-11-15T19:31:33.015Z",
 *             spaceId: "us_sp_YOUR_ID"
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             id: "us_fl_YOUR_ID",
 *             name: "NewFileName",
 *             description: "This is a new test file",
 *             ext: "csv",
 *             mimetype: "text/csv",
 *             encoding: "7bit",
 *             status: Flatfile.ModelFileStatusEnum.Partial,
 *             mode: Flatfile.Mode.Import,
 *             size: 81953,
 *             bytesReceived: 81593,
 *             createdAt: "2023-11-15T19:31:33.015Z",
 *             updatedAt: "2023-11-15T19:31:33.015Z",
 *             spaceId: "us_sp_YOUR_ID"
 *         }
 *     }
 *
 * @example
 *     {
 *         data: {
 *             id: "us_file_1234567890abcdef",
 *             name: "Cloned Test File",
 *             description: "This is a cloned test file",
 *             ext: "csv",
 *             mimetype: "text/csv",
 *             encoding: "7bit",
 *             status: Flatfile.ModelFileStatusEnum.Partial,
 *             mode: Flatfile.Mode.Import,
 *             size: 81953,
 *             bytesReceived: 81953,
 *             createdAt: "2023-11-15T19:32:45.123Z",
 *             updatedAt: "2023-11-15T19:32:45.123Z",
 *             spaceId: "us_sp_YOUR_ID"
 *         }
 *     }
 */
export interface FileResponse {
    data: Flatfile.File_;
}
