/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface ListFilesResponse {
    pagination?: Flatfile.Pagination;
    data: Flatfile.File_[];
}
