/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const DataRetentionPolicyEnum: core.serialization.Schema<
    serializers.DataRetentionPolicyEnum.Raw,
    Flatfile.DataRetentionPolicyEnum
> = core.serialization.enum_(["lastActivity", "sinceCreated"]);

export declare namespace DataRetentionPolicyEnum {
    type Raw = "lastActivity" | "sinceCreated";
}
