/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { Pagination } from "../../commons/types/Pagination";
import { File_ } from "./File_";

export const ListFilesResponse: core.serialization.ObjectSchema<
    serializers.ListFilesResponse.Raw,
    Flatfile.ListFilesResponse
> = core.serialization.object({
    pagination: Pagination.optional(),
    data: core.serialization.list(File_),
});

export declare namespace ListFilesResponse {
    interface Raw {
        pagination?: Pagination.Raw | null;
        data: File_.Raw[];
    }
}
