/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@flatfile/api";
import * as core from "../../../../core";

export const ModelFileStatusEnum: core.serialization.Schema<
    serializers.ModelFileStatusEnum.Raw,
    Flatfile.ModelFileStatusEnum
> = core.serialization.enum_(["partial", "complete", "archived", "purged", "failed"]);

export declare namespace ModelFileStatusEnum {
    type Raw = "partial" | "complete" | "archived" | "purged" | "failed";
}
