/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const Mode: core.serialization.Schema<serializers.Mode.Raw, Flatfile.Mode> = core.serialization.enum_([
    "import",
    "export",
]);

export declare namespace Mode {
    export type Raw = "import" | "export";
}
