/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../..";

/**
 * @example
 *     {}
 */
export interface ListPromptsRequest {
    /**
     * Type of prompt (default AI_ASSIST)
     */
    promptType?: Flatfile.PromptTypeQueryEnum;
    /**
     * Number of prompts to return in a page (default 7)
     */
    pageSize?: number;
    /**
     * Based on pageSize, which page of prompts to return
     */
    pageNumber?: number;
}
