/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { Environment } from "./Environment";

export const EnvironmentResponse: core.serialization.ObjectSchema<
    serializers.EnvironmentResponse.Raw,
    Flatfile.EnvironmentResponse
> = core.serialization.object({
    data: Environment,
});

export declare namespace EnvironmentResponse {
    export interface Raw {
        data: Environment.Raw;
    }
}
