/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { GuideResource } from "./GuideResource";

export const GuideDetailResponse: core.serialization.ObjectSchema<
    serializers.GuideDetailResponse.Raw,
    Flatfile.GuideDetailResponse
> = core.serialization.object({
    data: GuideResource,
});

export declare namespace GuideDetailResponse {
    interface Raw {
        data: GuideResource.Raw;
    }
}
