/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const ListCommitsResponse: core.serialization.ObjectSchema<
    serializers.ListCommitsResponse.Raw,
    Flatfile.ListCommitsResponse
> = core.serialization.object({
    data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Commit)),
});

export declare namespace ListCommitsResponse {
    interface Raw {
        data: serializers.Commit.Raw[];
    }
}
