/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const CompositeUniqueConstraintStrategy: core.serialization.Schema<
    serializers.CompositeUniqueConstraintStrategy.Raw,
    Flatfile.CompositeUniqueConstraintStrategy
> = core.serialization.enum_(["hash", "concat"]);

export declare namespace CompositeUniqueConstraintStrategy {
    export type Raw = "hash" | "concat";
}
