/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { CompositeUniqueConstraintStrategy } from "./CompositeUniqueConstraintStrategy";

export const CompositeUniqueConstraint: core.serialization.ObjectSchema<
    serializers.CompositeUniqueConstraint.Raw,
    Flatfile.CompositeUniqueConstraint
> = core.serialization.object({
    name: core.serialization.string(),
    fields: core.serialization.list(core.serialization.string()),
    requiredFields: core.serialization.list(core.serialization.string()).optional(),
    strategy: CompositeUniqueConstraintStrategy,
});

export declare namespace CompositeUniqueConstraint {
    interface Raw {
        name: string;
        fields: string[];
        requiredFields?: string[] | null;
        strategy: CompositeUniqueConstraintStrategy.Raw;
    }
}
