/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@flatfile/api-beta";
import * as core from "../../../../core";

export const CreateSheetVersionResponse: core.serialization.ObjectSchema<
    serializers.CreateSheetVersionResponse.Raw,
    Flatfile.CreateSheetVersionResponse
> = core.serialization.object({
    data: core.serialization.lazy(async () => (await import("../../..")).VersionId),
});

export declare namespace CreateSheetVersionResponse {
    interface Raw {
        data: serializers.VersionId.Raw;
    }
}
