/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@flatfile/api-beta";
import * as core from "../../../../core";

export const FieldsData: core.serialization.Schema<serializers.FieldsData.Raw, Flatfile.FieldsData> =
    core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).FieldData));

export declare namespace FieldsData {
    type Raw = serializers.FieldData.Raw[];
}
