/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@fern-api/flatfile";
import * as core from "../../../../core";

export const RecordDataWithLinks: core.serialization.Schema<
    serializers.RecordDataWithLinks.Raw,
    Flatfile.RecordDataWithLinks
> = core.serialization.record(
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("../../..")).CellValueWithLinks).optional()
);

export declare namespace RecordDataWithLinks {
    type Raw = Record<string, serializers.CellValueWithLinks.Raw | null | undefined>;
}
