/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { RecordCountsResponseData } from "./RecordCountsResponseData";

export const RecordCountsResponse: core.serialization.ObjectSchema<
    serializers.RecordCountsResponse.Raw,
    Flatfile.RecordCountsResponse
> = core.serialization.object({
    data: RecordCountsResponseData,
});

export declare namespace RecordCountsResponse {
    export interface Raw {
        data: RecordCountsResponseData.Raw;
    }
}
