/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { CompositeUniqueConstraint } from "./CompositeUniqueConstraint";
import { ExternalSheetConstraint } from "./ExternalSheetConstraint";

export const SheetConstraint: core.serialization.Schema<serializers.SheetConstraint.Raw, Flatfile.SheetConstraint> =
    core.serialization
        .union("type", {
            unique: CompositeUniqueConstraint,
            external: ExternalSheetConstraint,
        })
        .transform<Flatfile.SheetConstraint>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace SheetConstraint {
    export type Raw = SheetConstraint.Unique | SheetConstraint.External;

    export interface Unique extends CompositeUniqueConstraint.Raw {
        type: "unique";
    }

    export interface External extends ExternalSheetConstraint.Raw {
        type: "external";
    }
}
