/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The name of a secret. Minimum 1 character, maximum 1024
 *
 * @example
 *     "SOMESERVICE_APIKEY"
 */
export type SecretName = string;
