/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@fern-api/flatfile";

/**
 * Properties used to allow users to connect to the event bus
 */
export interface EventToken {
    accountId?: Flatfile.AccountId;
    /** The id of the event bus to subscribe to */
    subscribeKey?: string;
    /** Time to live in minutes */
    ttl?: number;
    token?: string;
}
