/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { BooleanPropertyConfig } from "./BooleanPropertyConfig";
import { BaseProperty } from "./BaseProperty";

export const BooleanProperty: core.serialization.ObjectSchema<
    serializers.BooleanProperty.Raw,
    Flatfile.BooleanProperty
> = core.serialization
    .object({
        config: BooleanPropertyConfig.optional(),
    })
    .extend(BaseProperty);

export declare namespace BooleanProperty {
    export interface Raw extends BaseProperty.Raw {
        config?: BooleanPropertyConfig.Raw | null;
    }
}
