/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { UniqueConstraint } from "./UniqueConstraint";
import { ExternalConstraint } from "./ExternalConstraint";
import { StoredConstraint } from "./StoredConstraint";

export const Constraint: core.serialization.Schema<serializers.Constraint.Raw, Flatfile.Constraint> = core.serialization
    .union("type", {
        required: core.serialization.object({}),
        unique: UniqueConstraint,
        computed: core.serialization.object({}),
        external: ExternalConstraint,
        stored: StoredConstraint,
    })
    .transform<Flatfile.Constraint>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace Constraint {
    export type Raw =
        | Constraint.Required
        | Constraint.Unique
        | Constraint.Computed
        | Constraint.External
        | Constraint.Stored;

    export interface Required {
        type: "required";
    }

    export interface Unique extends UniqueConstraint.Raw {
        type: "unique";
    }

    export interface Computed {
        type: "computed";
    }

    export interface External extends ExternalConstraint.Raw {
        type: "external";
    }

    export interface Stored extends StoredConstraint.Raw {
        type: "stored";
    }
}
