/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const EnumPropertyOption: core.serialization.ObjectSchema<
    serializers.EnumPropertyOption.Raw,
    Flatfile.EnumPropertyOption
> = core.serialization.object({
    label: core.serialization.string().optional(),
    color: core.serialization.string().optional(),
    icon: core.serialization.string().optional(),
    meta: core.serialization.record(core.serialization.string(), core.serialization.any()).optional(),
    value: core.serialization.any(),
});

export declare namespace EnumPropertyOption {
    interface Raw {
        label?: string | null;
        color?: string | null;
        icon?: string | null;
        meta?: Record<string, any> | null;
        value?: any;
    }
}
