/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@flatfile/api-beta";
import * as core from "../../../../core";

export const NumberProperty: core.serialization.ObjectSchema<serializers.NumberProperty.Raw, Flatfile.NumberProperty> =
    core.serialization
        .object({
            config: core.serialization.lazyObject(async () => (await import("../../..")).NumberConfig).optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseProperty))
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).ArrayableProperty));

export declare namespace NumberProperty {
    interface Raw extends serializers.BaseProperty.Raw, serializers.ArrayableProperty.Raw {
        config?: serializers.NumberConfig.Raw | null;
    }
}
