/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { ReferenceFilter } from "./ReferenceFilter";

export const ReferenceListPropertyConfig: core.serialization.ObjectSchema<
    serializers.ReferenceListPropertyConfig.Raw,
    Flatfile.ReferenceListPropertyConfig
> = core.serialization.object({
    ref: core.serialization.string(),
    key: core.serialization.string(),
    filter: ReferenceFilter.optional(),
});

export declare namespace ReferenceListPropertyConfig {
    export interface Raw {
        ref: string;
        key: string;
        filter?: ReferenceFilter.Raw | null;
    }
}
