/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const StoredConstraint: core.serialization.ObjectSchema<
    serializers.StoredConstraint.Raw,
    Flatfile.StoredConstraint
> = core.serialization.object({
    validator: core.serialization.string(),
    version: core.serialization.number().optional(),
    description: core.serialization.string().optional(),
    label: core.serialization.string().optional(),
    config: core.serialization.any().optional(),
});

export declare namespace StoredConstraint {
    interface Raw {
        validator: string;
        version?: number | null;
        description?: string | null;
        label?: string | null;
        config?: any | null;
    }
}
