/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@fern-api/flatfile";
import * as core from "../../../../core";

export const UniqueConstraint: core.serialization.ObjectSchema<
    serializers.UniqueConstraint.Raw,
    Flatfile.UniqueConstraint
> = core.serialization.object({
    config: core.serialization.lazyObject(async () => (await import("../../..")).UniqueConstraintConfig).optional(),
});

export declare namespace UniqueConstraint {
    interface Raw {
        config?: serializers.UniqueConstraintConfig.Raw | null;
    }
}
