/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const RoutineType: core.serialization.Schema<serializers.RoutineType.Raw, Flatfile.RoutineType> =
    core.serialization.enum_(["JOB"]);

export declare namespace RoutineType {
    type Raw = "JOB";
}
