/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     Flatfile.RoutineType.Job
 */
export type RoutineType = "JOB";

export const RoutineType = {
    Job: "JOB",
} as const;
