/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments-v2";
import * as core from "../../../../core-v2";
import { Records } from "../resources/records/client/Client";
import { Workbooks } from "../resources/workbooks/client/Client";

export declare namespace V2 {
    export interface Options {
        environment?: core.Supplier<environments.FlatfileV2Environment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Override the X-Disable-Hooks header */
        xDisableHooks?: "true";
        fetcher?: core.FetchFunction;
    }
}

export class V2 {
    protected _records: Records | undefined;
    protected _workbooks: Workbooks | undefined;

    constructor(protected readonly _options: V2.Options) {}

    public get records(): Records {
        return (this._records ??= new Records(this._options));
    }

    public get workbooks(): Workbooks {
        return (this._workbooks ??= new Workbooks(this._options));
    }
}
