/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../../index";

/**
 * @example
 *     {
 *         sheetId: "sheetId",
 *         environmentId: "environmentId",
 *         spaceId: "spaceId",
 *         workbookId: "workbookId",
 *         analyses: [{
 *                 field: "field",
 *                 result: {
 *                     "key": "value"
 *                 }
 *             }, {
 *                 field: "field",
 *                 result: {
 *                     "key": "value"
 *                 }
 *             }]
 *     }
 */
export interface CreateAnalysisRequest {
    sheetId: Flatfile.SheetId;
    environmentId: Flatfile.EnvironmentId;
    spaceId: Flatfile.SpaceId;
    workbookId: Flatfile.WorkbookId;
    /** List of analysis results to upsert */
    analyses: Flatfile.AnalysisCreateDto[];
}
