/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@fern-api/flatfile";

/**
 * A log of an agent execution
 *
 * @example
 *     {
 *         eventId: "us_evt_9cuesESa7W9cuesE",
 *         success: true,
 *         createdAt: "2022-09-18T00:19:57.007Z",
 *         log: "SUCCESS"
 *     }
 */
export interface AgentLog {
    eventId: Flatfile.EventId;
    /** Whether the agent execution was successful */
    success: boolean;
    createdAt: string;
    /** The log of the agent execution */
    log?: string;
}
