/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as FlatfileV2 from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { WorkbookId } from "../../../../commons/types/WorkbookId";

export const BulkCreateWorkbookResponse: core.serialization.ObjectSchema<
    serializers.v2.BulkCreateWorkbookResponse.Raw,
    FlatfileV2.v2.BulkCreateWorkbookResponse
> = core.serialization.object({
    id: WorkbookId,
    name: core.serialization.string(),
});

export declare namespace BulkCreateWorkbookResponse {
    export interface Raw {
        id: WorkbookId.Raw;
        name: string;
    }
}
