/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../..";

/**
 * @example
 *     {
 *         sheetId: "us_sh_YOUR_ID",
 *         label: "My snapshot"
 *     }
 */
export interface CreateSnapshotRequest {
    /** ID of sheet */
    sheetId: Flatfile.SheetId;
    /** Label for the snapshot */
    label?: string;
    /** ThreadId for the snapshot */
    threadId?: string;
}
