/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

export interface AnalysisResponse {
    data: Flatfile.AnalysisData[];
    /** Pagination and other metadata */
    meta?: any;
}
