/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { MappingRuleConfig } from "./MappingRuleConfig";

export const CreateMappingRulesRequest: core.serialization.Schema<
    serializers.CreateMappingRulesRequest.Raw,
    Flatfile.CreateMappingRulesRequest
> = core.serialization.list(MappingRuleConfig);

export declare namespace CreateMappingRulesRequest {
    type Raw = MappingRuleConfig.Raw[];
}
