/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Flatfile from "../../../../../api";
import * as core from "../../../../../core";

export const CreateSnapshotRequest: core.serialization.Schema<
    serializers.CreateSnapshotRequest.Raw,
    Flatfile.CreateSnapshotRequest
> = core.serialization.object({
    label: core.serialization.string().optional(),
});

export declare namespace CreateSnapshotRequest {
    interface Raw {
        label?: string | null;
    }
}
