/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@flatfile/api";

export interface GetEventTokenRequest {
    /**
     * The space id
     */
    spaceId: Flatfile.SpaceId;
}
