/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@fern-api/flatfile";

/**
 * Properties used to create a new Space Config
 */
export interface SpacePatternConfig {
    slug: string;
    name: string;
    blueprints: Flatfile.spaces.Blueprint[];
    actions?: Flatfile.Action[];
}
