/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A version of a guide
 *
 * @example
 *     {
 *         id: "us_gu_123",
 *         version: 1,
 *         content: "# Getting Started\nWelcome to the guide...",
 *         createdAt: "2023-10-30T16:59:45.735Z",
 *         updatedAt: "2023-10-30T16:59:45.735Z"
 *     }
 */
export interface GuideVersionResource {
    id: string;
    version: number;
    content: string;
    createdAt: Date;
    updatedAt: Date;
}
