/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

export interface CategoryMapping {
    /** The source value to map from */
    sourceValue?: Flatfile.EnumValue;
    /** The destination value to map to */
    destinationValue?: Flatfile.EnumValue;
}
