/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The configuration for an onboarding job
 */
export interface ConfigureDemoJobConfig {
    /** The name of the company */
    companyName: string;
}
