/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@flatfile/api-beta";

/**
 * The configuration for a delete job
 */
export interface DeleteJobConfig {
    filter: Flatfile.Filter;
    /** Name of field by which to filter records */
    filterField?: string;
    sheet: Flatfile.SheetId;
    exceptions?: Flatfile.RecordId[];
}
