/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flatfile } from "@flatfile/api-beta";

/**
 * Only available if one or more of the destination fields is of type enum. Provides category mapping.
 */
export interface EnumDetails {
    mapping?: Flatfile.CategoryMapping[];
    unusedSourceValues?: string[];
    unusedDestinationValues?: string[];
}
