/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

export type JobOutcomeTrigger = Flatfile.JobOutcomeTriggerType | Flatfile.JobOutcomeTriggerDetails;
