/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "us_jb_YOUR_ID"
 *     }
 */
export interface JobOutcomeNextId {
    id: string;
    label?: string;
}
