/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

/**
 * Info about the number of parts to create
 */
export type JobParts = number | Flatfile.JobPartsArray;
