/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

export type JobUpdateConfig =
    | Flatfile.DeleteRecordsJobConfig
    | Flatfile.FileJobConfig
    | Flatfile.PipelineJobConfig
    | Flatfile.ExportJobConfig
    | Flatfile.MutateJobConfig
    | Flatfile.FindAndReplaceJobConfig
    | Flatfile.MappingProgramJobConfig
    | Flatfile.AiGenerateBlueprintJobConfig
    | Flatfile.AiGenerateSampleDataJobConfig
    | Flatfile.AiGenerateBlueprintConstraintsJobConfig
    | Flatfile.AiGenerateConstraintJobConfig
    | Flatfile.AiRuleCreationJobConfig
    | Flatfile.CaptureRoutineJobConfig
    | Flatfile.RunRunbookJobConfig
    | Flatfile.MappingFromPreprocessingJobConfig
    | Flatfile.EmptyObject
    | Flatfile.AddRecordsToDataClipJobConfig
    | Flatfile.UpdateDataClipResolutionsJobConfig
    | Flatfile.AgentExportJobConfig
    | Flatfile.CompanyResearchJobConfig
    | Flatfile.ConfigureDemoJobConfig;
