/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export type JobUpdateConfig =
    | Flatfile.DeleteRecordsJobConfig
    | Flatfile.FileJobConfig
    | Flatfile.PipelineJobConfig
    | Flatfile.ExportJobConfig
    | Flatfile.MutateJobConfig
    | Flatfile.FindAndReplaceJobConfig
    | Flatfile.MappingProgramJobConfig
    | Flatfile.AiGenerateBlueprintJobConfig
    | Flatfile.AppAutobuildDeployJobConfig
    | Flatfile.AiGenerateSampleDataJobConfig
    | Flatfile.AiGenerateBlueprintConstraintsJobConfig
    | Flatfile.AiGenerateConstraintJobConfig
    | Flatfile.AiRuleCreationJobConfig
    | Flatfile.EmptyObject
    | Flatfile.AddRecordsToDataClipJobConfig
    | Flatfile.UpdateDataClipResolutionsJobConfig;
