/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

export interface MappingProgramJobConfig {
    sourceSheetId: Flatfile.SheetId;
    destinationSheetId: Flatfile.SheetId;
    mappingRules: Record<string, any>[];
    canRecompute?: boolean;
}
