/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface MutateJobConfig {
    sheetId: Flatfile.SheetId;
    /** A JavaScript function that will be run on each record in the sheet, it should return a mutated record. */
    mutateRecord: string;
    /** If the mutation was generated through some sort of id-ed process, this links this job and that process. */
    mutationId?: string;
    /** If specified, a snapshot will be generated with this label */
    snapshotLabel?: string;
    filter?: Flatfile.Filter;
    filterField?: Flatfile.FilterField;
    searchValue?: Flatfile.SearchValue;
    searchField?: Flatfile.SearchField;
    q?: string;
    /** The Record Ids param (ids) is a list of record ids that can be passed to several record endpoints allowing the user to identify specific records to INCLUDE in the query, or specific records to EXCLUDE, depending on whether or not filters are being applied. When passing a query param that filters the record dataset, such as 'searchValue', or a 'filter' of 'valid' | 'error' | 'all', the 'ids' param will EXCLUDE those records from the filtered results. For basic queries that do not filter the dataset, passing record ids in the 'ids' param will limit the dataset to INCLUDE just those specific records */
    ids?: Flatfile.RecordId[];
}
