/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const AppsResponse: core.serialization.ObjectSchema<serializers.AppsResponse.Raw, Flatfile.AppsResponse> =
    core.serialization.object({
        data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).App)),
    });

export declare namespace AppsResponse {
    interface Raw {
        data: serializers.App.Raw[];
    }
}
