/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { ConstraintVersionResource } from "./ConstraintVersionResource";

export const ConstraintVersionsResponse: core.serialization.ObjectSchema<
    serializers.ConstraintVersionsResponse.Raw,
    Flatfile.ConstraintVersionsResponse
> = core.serialization.object({
    data: core.serialization.list(ConstraintVersionResource),
});

export declare namespace ConstraintVersionsResponse {
    export interface Raw {
        data: ConstraintVersionResource.Raw[];
    }
}
