/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@flatfile/api-beta";
import * as core from "../../../../core";

export const ExchangeTokenResponse: core.serialization.ObjectSchema<
    serializers.ExchangeTokenResponse.Raw,
    Flatfile.ExchangeTokenResponse
> = core.serialization.object({
    data: core.serialization.lazyObject(async () => (await import("../../..")).ExchangeTokenData),
});

export declare namespace ExchangeTokenResponse {
    interface Raw {
        data: serializers.ExchangeTokenData.Raw;
    }
}
