/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

export interface ConstraintCreate {
    description?: string;
    function?: string;
    options?: any;
    label?: string;
    validator?: string;
    appId?: Flatfile.AppId;
}
