/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An entitlement belonging to a resource
 *
 * @example
 *     {
 *         key: "snapshots",
 *         description: "When enabled, snapshots to be taken.",
 *         influencesPrivileges: ["snapshot:create"],
 *         metadata: {
 *             "files": 10
 *         },
 *         createdAt: new Date("2023-11-15T19:31:33.015Z"),
 *         updatedAt: new Date("2023-11-15T19:31:33.015Z")
 *     }
 */
export interface Entitlement {
    /** Short name for the entitlement */
    key: string;
    /** Description for the entitlement */
    description: string;
    /** List of privilege names impacted by this entitlement */
    influencesPrivileges: string[];
    /** Contains conditions or limits for an entitlement */
    metadata?: any;
    /** Date the entitlement was created */
    createdAt: Date;
    /** Date the entitlement was last updated */
    updatedAt: Date;
}
