/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { SpaceId } from "../../commons/types/SpaceId";
import { GuestWorkbook } from "./GuestWorkbook";
import { GuestSheet } from "./GuestSheet";

export const GuestSpace: core.serialization.ObjectSchema<serializers.GuestSpace.Raw, Flatfile.GuestSpace> =
    core.serialization.object({
        id: SpaceId,
        workbooks: core.serialization.list(GuestWorkbook).optional(),
        sheets: core.serialization.list(GuestSheet).optional(),
        lastAccessed: core.serialization.date().optional(),
    });

export declare namespace GuestSpace {
    export interface Raw {
        id: SpaceId.Raw;
        workbooks?: GuestWorkbook.Raw[] | null;
        sheets?: GuestSheet.Raw[] | null;
        lastAccessed?: string | null;
    }
}
