/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const Invite: core.serialization.ObjectSchema<serializers.Invite.Raw, Flatfile.Invite> =
    core.serialization.object({
        guestId: core.serialization.lazy(async () => (await import("../../..")).GuestId),
        spaceId: core.serialization.lazy(async () => (await import("../../..")).SpaceId),
        fromName: core.serialization.string().optional(),
        message: core.serialization.string().optional(),
    });

export declare namespace Invite {
    interface Raw {
        guestId: serializers.GuestId.Raw;
        spaceId: serializers.SpaceId.Raw;
        fromName?: string | null;
        message?: string | null;
    }
}
