/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

/**
 * @example
 *     {
 *         type: Flatfile.DataRetentionPolicyEnum.LastActivity,
 *         period: 5,
 *         environmentId: "us_env_YOUR_ID"
 *     }
 */
export interface DataRetentionPolicyConfig {
    type: Flatfile.DataRetentionPolicyEnum;
    period: number;
    environmentId: Flatfile.EnvironmentId;
}
