/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface Action {
    slug?: string;
    operation?: string;
    mode?: Flatfile.ActionMode;
    label: string;
    type?: string;
    description?: string;
    primary?: boolean;
    confirm?: boolean;
}
