/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../../index";

/**
 * Data required to create a new onboarding
 *
 * @example
 *     {
 *         userId: "us_usr_789ghi"
 *     }
 */
export interface OnboardingCreate {
    userId: Flatfile.UserId;
}
