/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of onboarding flow
 */
export type OnboardingFlow = "buildmode" | "workflow";
export const OnboardingFlow = {
    Buildmode: "buildmode",
    Workflow: "workflow",
} as const;
