/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { AgentExportId } from "../../commons/types/AgentExportId";
import { AgentId } from "../../commons/types/AgentId";
import { AgentExportType } from "./AgentExportType";
import { AccountId } from "../../commons/types/AccountId";
import { EnvironmentId } from "../../commons/types/EnvironmentId";

export const AgentExport: core.serialization.ObjectSchema<serializers.AgentExport.Raw, Flatfile.AgentExport> =
    core.serialization.object({
        id: AgentExportId,
        agentId: AgentId,
        exportType: AgentExportType,
        accountId: AccountId,
        environmentId: EnvironmentId,
        createdAt: core.serialization.date(),
        updatedAt: core.serialization.date(),
        deletedAt: core.serialization.date().optional(),
    });

export declare namespace AgentExport {
    export interface Raw {
        id: AgentExportId.Raw;
        agentId: AgentId.Raw;
        exportType: AgentExportType.Raw;
        accountId: AccountId.Raw;
        environmentId: EnvironmentId.Raw;
        createdAt: string;
        updatedAt: string;
        deletedAt?: string | null;
    }
}
