/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { AgentExport } from "./AgentExport";
import { Pagination } from "../../commons/types/Pagination";

export const ListAgentExportsResponse: core.serialization.ObjectSchema<
    serializers.ListAgentExportsResponse.Raw,
    Flatfile.ListAgentExportsResponse
> = core.serialization.object({
    data: core.serialization.list(AgentExport),
    pagination: Pagination,
});

export declare namespace ListAgentExportsResponse {
    interface Raw {
        data: AgentExport.Raw[];
        pagination: Pagination.Raw;
    }
}
