/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface ProgramConfig {
    /** Source schema */
    source: Flatfile.SheetConfig;
    /** Destination schema */
    destination: Flatfile.SheetConfig;
    /** ID of the family to add the program to */
    familyId?: Flatfile.FamilyId;
    /** Namespace of the program */
    namespace?: string;
    /** Whether to save the program for editing later. Defaults to false. If true, the response will contain an ID and access token. */
    save?: boolean;
    /** Mapping rules to use for the program. If present, the program will be created with these rules. */
    rules?: Flatfile.MappingRuleConfig[];
}
