/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flatfile from "../../..";

export interface ProgramConfig {
    /** Source schema */
    source: Flatfile.SheetConfig;
    /** Destination schema */
    destination: Flatfile.SheetConfig;
    /** Whether to save the program for editing later. Defaults to false. If true, the response will contain an ID and access token. */
    save?: boolean;
}
