/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";
import { TransformationApiData } from "./TransformationApiData";

export const TransformationResponse: core.serialization.ObjectSchema<
    serializers.TransformationResponse.Raw,
    Flatfile.TransformationResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: TransformationApiData,
});

export declare namespace TransformationResponse {
    export interface Raw {
        success: boolean;
        data: TransformationApiData.Raw;
    }
}
