/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const ActionSchedule: core.serialization.Schema<serializers.ActionSchedule.Raw, Flatfile.ActionSchedule> =
    core.serialization.enum_(["weekly", "daily", "hourly"]);

export declare namespace ActionSchedule {
    type Raw = "weekly" | "daily" | "hourly";
}
