/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const ActionMountField: core.serialization.ObjectSchema<
    serializers.ActionMountField.Raw,
    Flatfile.ActionMountField
> = core.serialization.object({
    keys: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace ActionMountField {
    export interface Raw {
        keys?: string[] | null;
    }
}
