/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";
import { Action } from "./Action";

export const ApiActionConfig: core.serialization.ObjectSchema<
    serializers.ApiActionConfig.Raw,
    Flatfile.ApiActionConfig
> = core.serialization
    .object({
        targetId: core.serialization.string(),
    })
    .extend(Action);

export declare namespace ApiActionConfig {
    interface Raw extends Action.Raw {
        targetId: string;
    }
}
