/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const CanvasId: core.serialization.Schema<serializers.CanvasId.Raw, Flatfile.CanvasId> =
    core.serialization.string();

export declare namespace CanvasId {
    type Raw = string;
}
