/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const FileId: core.serialization.Schema<serializers.FileId.Raw, Flatfile.FileId> = core.serialization.string();

export declare namespace FileId {
    export type Raw = string;
}
