/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const Filter: core.serialization.Schema<serializers.Filter.Raw, Flatfile.Filter> = core.serialization.enum_([
    "valid",
    "error",
    "all",
    "none",
]);

export declare namespace Filter {
    export type Raw = "valid" | "error" | "all" | "none";
}
