/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const Guardrail: core.serialization.ObjectSchema<serializers.Guardrail.Raw, Flatfile.Guardrail> =
    core.serialization.object({
        content: core.serialization.string(),
    });

export declare namespace Guardrail {
    interface Raw {
        content: string;
    }
}
