/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const JsonPathString: core.serialization.Schema<serializers.JsonPathString.Raw, Flatfile.JsonPathString> =
    core.serialization.string();

export declare namespace JsonPathString {
    type Raw = string;
}
