/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flatfile from "../../../../api/index";
import * as core from "../../../../core";

export const MappingId: core.serialization.Schema<serializers.MappingId.Raw, Flatfile.MappingId> =
    core.serialization.string();

export declare namespace MappingId {
    export type Raw = string;
}
