/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flatfile from "../../../../api";
import * as core from "../../../../core";

export const PromptId: core.serialization.Schema<serializers.PromptId.Raw, Flatfile.PromptId> =
    core.serialization.string();

export declare namespace PromptId {
    type Raw = string;
}
