/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@flatfile/api";
import * as core from "../../../../core";

export const Success: core.serialization.ObjectSchema<serializers.Success.Raw, Flatfile.Success> =
    core.serialization.object({
        data: core.serialization.lazyObject(async () => (await import("../../..")).SuccessData),
    });

export declare namespace Success {
    interface Raw {
        data: serializers.SuccessData.Raw;
    }
}
