/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Flatfile } from "@flatfile/api";
import * as core from "../../../../core";

export const VersionId: core.serialization.Schema<serializers.VersionId.Raw, Flatfile.VersionId> =
    core.serialization.string();

export declare namespace VersionId {
    type Raw = string;
}
